### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by xueharry** [Harvard-ATG/canvas_syllabus_export#2]
It would be great if you could look at views.py, index.html, apirequest.py and syllabuspdf_extras.py.

views.py- I'm wondering if there is potentially a better way to distinguish between the initial load of the page or another GET request. The way I'm handling it right now is kind of hackerish with a hidden field.
index.html- Pointers on html and css style/best practices would be great since I'm a newb.
apirequest.py- Functions for generating requests to the Canvas API as well as helpers to sort responses.
syllabuspdf_extras.py- Custom filters and tags for displaying data from the API in a more readable format.

**Comment by condaatje** [comment]
**Views.py:**
    -- This could use a couple quick comments, though the code is clean and well-named.
    -- Also, it would be nice to see dictionaries expanded for readability

**Index.py**
    -- A quick comment summarizing the mechanism and output of the form would help (like "this prints the syllabus through the _ javascript method call")
    -- A comment in front of each block of conditional html explaining the decision will also help someone trying to skim through
    -- CSS at the bottom is likely necessary, so explain to whoever might be maintaining the code why it will break things if he/she moves it

**APIRequest.py:**
    -- Well commented
    -- Seems to do a good job of optimizing wait times by sending specific requests: longer urls essentially are memoization, more specific ones (many functions) are data culling. Nice.

**Syllabus_Extras.py:**
    -- mostly straightforward
    -- how safe is this block of code?:
```python
        # Clean strings, cutting out last six characters
	cleanedstart = sub("[^0-9]", "", startat[0:20])
	cleanedend = sub("[^0-9]", "", endat[0:20])
```
    -- is this always going to be OK?:
         "If start_at and end_at are the same, the event is an assignment"
    -- I'd like to learn about @register-filter, seems useful

**Comment by arthurian** [comment]
Hi Harry,

Nice job :+1: . The code is well organized and very readable. Here are a few comments/suggestions that occurred to me as I looked over the code.

1. In **views.py**: an alternative to the hidden field approach would be to create two separate view functions, one that renders the syllabus with default settings, and another that renders the syllabus with settings submitted by a form. 

    index <------- GET index view
    index  -------> returns view rendered with default form selections
    detail <------- GET detail view (settings submitted via form)
    detail -------> returns view rendered with the form settings

    This would eliminate the need for a flag (the hidden field) that would tell the view whether it's a form submission or not. If the "detail" view is being requested, it's assumed that it's a form submission. This approach might be a little cleaner, but it would require some refactoring because the logic for both views is more or less the same.

2. In **views.py**: it might be good to return an HTTP 404 response code if this ```courseid = request.session['LTI_LAUNCH']['custom_canvas_course_id']``` fails. So instead of ```return HttpResponse("Course ID not found")``` you might do ```raise Http404("Course ID not found")```. See also: [django.http.Http404](https://docs.djangoproject.com/en/1.8/topics/http/views/#django.http.Http404)
3. In **syllabuspdf_extra.py**: I notice that you're parsing the ISO8601 dates and times by stripping non-numeric characters. When the date is formatted like YYYY-MM-DDTHH:MM:SSZ that should work well, but it seems like it would fail if the date is formatted like YYYY-MM-DDTHH:MM:SS+/-hh:mm (i.e. with timezone offset like -06:00). Do we know if Canvas always returns the date string in the former format?
 
    If this is an assumption we're making, it should be documented in the docstring for the function.
    One thing we could do to guard against a potential issue, is to gracefully fail if an exception is raised in **format_date()**. Looking at the python documentation for strptime, it seems like a ValueError exception would be raised if the string couldn't be parsed, so you could fallback to just returning the unformatted date string if that happened:
    ```python
    try:
        dformatted = convert_tz(datetime.strptime(cleaned, "%Y%m%d%H%M%S"))
        date = dformatted.strftime('%a %b %d, %Y')
    except ValueError:
        date = str
    ```
4. In **syllabuspdf_extra.py**: This is a tiny style thing, but just FYI that it would be more idiomatic to write:

    ```cleaned = sub("[^0-9]", "", str)```

    like this:

    ```cleaned = re.sub("[^0-9]", "", str)```

**Comment by arthurian** [comment]
@xueharry Feel free to close this issue. We'll do subsequent code reviews in pull requests.
